name: build

on:
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: build
      run: go build main.go

    - name: store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: main

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: get artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: main

    - name: deploy
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
        echo "ssh connect"
        scp main ${SSH_USER}@${SSH_HOST}:~/shared
        ssh ${SSH_USER}@${SSH_HOST} 'pkill shared;'
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_HOST_KEY: ${{ secrets.SSH_HOST_KEY }}